---
title: "Introduction and Motivation"
description: |
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Introduction

“Correlation does not imply causation.” You might have heard this saying from your intro statistics course, and we knew if we’d like to find some evidence that makes us believe the causation. In causal inference, we will investigate the causal relationship between treatment (policy/ dosage/ drug/ habits, etc.) and the outcome of interest. By assigning people to different groups, we try to use various methods to reach the causal conclusion on which group has a better outcome? To do this, we should estimate the “causal effect”. 

A common way of estimating this is to calculate the **average causal effect (ACE)**, denoted by:
$E[Y^{a=1}]- E[Y^{a=0}]$. 

In this formula, a represents the potential treatment assignment: $a=0$ means the individual will not be assigned treatment (control), and $a=1$ dictates receiving treatment. In causal inference study, a huge blind spot is that after we observe the data, we want to know what would happen to an individual if they were to be assigned into the other group; unfortunately, this can never happen. As a result, we use capital $A$ to represent the actual treatment received, and $a$ for potential treatment under causal inference studies. $Y$ is the outcome - it can be either quantitative or indicative. Combining together, the formula above makes sense: it records the average difference in the potential outcome between treatment and control group.

In statistics, after defining some particular interests and writing them out as mathematical formulas, researchers look for **estimators** to estimate the true parameter (in our case, that is the ACE). **Doubly Robust Estimator (DRE)** is a nice one due to its unbiasedness, meaning its average is equivalent to the true value of parameter (ACE). The reason it is called “doubly” is from the fact that DRE is composed of two different estimators: Inverse Probability Weighting (IPW), and Outcome Regression Model (REG). While this may not make any sense, don’t worry - in the next section, “Regression and IPW”, we will firstly go through these two regular, popular approaches in estimating ACE, and see how our doubly robust estimator serves to combine them and become even more powerful!

# Motivation of the project

Estimating causal effects from data is a fundamental problem in many fields, including health care, economics, and many (social) sciences subjects. Xiang comes from an economic background whereas Kristy comes from a biology background. We teamed up and decided to explore this new, popular method, Doubly Robust estimation (DRE), which is widely used in biostatistics and econometric applications in many Difference-in-Difference (DiD, another way to say we are examining causal effects) experiments and causal inference contexts. 
